/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_tuba_utils_TubaUtils */

#ifndef _Included_com_jack_tuba_utils_TubaUtils
#define _Included_com_jack_tuba_utils_TubaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jack_tuba_utils_TubaUtils
 * Method:    getMainUrl
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_tuba_utils_TubaUtils_getMainUrl
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
